openapi: 3.0.3
info:
  title: Owner Service v1
  description: |-
    API for Owner Service
  termsOfService: http://swagger.io/terms/
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: Owner
    description: owner who lists a car
paths:
  /api/v1/owner:
    post:
      tags:
        - Owner
      summary: Add an Owner to the system
      description: Create a new Owner
      operationId: createOwner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiOwner'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiOwner'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    get:
      tags:
        - Owner
      summary: Get all Owners from the system
      description: Get all Owners from the system
      operationId: getOwners
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiOwners'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'


components:
  schemas:
    ApiOwner:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 'Abdullah'
        email:
          type: string
          example: 'abdullah@example.com'
    OwnerCreatedEvent:
      type: object
      properties:
        owner:
          $ref: '#/components/schemas/ApiOwner'
    ApiOwners:
      type: array
      items:
        $ref: '#/components/schemas/ApiOwner'
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '2300'
        message:
          type: string
          description: 'Brief explanation about the error, for more information consult the Car Service team'
